# Generated by Django 4.2.1 on 2023-05-31 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
