# Generated by Django 4.2.1 on 2023-06-19 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='poll',
            new_name='post',
        ),
    ]
