# Generated by Django 4.2.1 on 2023-07-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_tag_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='post',
        ),
    ]
