# Generated by Django 4.2.1 on 2023-07-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_tag_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
