# Generated by Django 4.2 on 2023-08-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_comment_is_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='reply',
            name='parent_reply_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
