# Generated by Django 4.2 on 2023-08-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_choice_options_alter_reply_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='parent_reply_id',
            field=models.CharField(max_length=255),
        ),
    ]
