# Generated by Django 4.2 on 2023-08-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_reply_parent_reply_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='parent_reply_id',
        ),
        migrations.AddField(
            model_name='reply',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
