# Generated by Django 4.2 on 2023-09-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_repost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repost',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='repost',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
