# Generated by Django 4.2 on 2023-09-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='content',
        ),
    ]
