# Generated by Django 4.2 on 2023-09-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_useractivity_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
