# Generated by Django 4.2 on 2023-09-21 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.reply'),
        ),
    ]
