# Generated by Django 4.2 on 2023-09-21 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_notification_second_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='second_user',
        ),
    ]
