# Generated by Django 4.2.1 on 2023-07-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_inbox'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inbox',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='receivers',
        ),
    ]
