# Generated by Django 4.2 on 2023-08-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_alter_circle_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='host',
            new_name='user',
        ),
    ]
