# Generated by Django 4.2 on 2023-08-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_rename_host_circle_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CirclePost',
        ),
    ]
