# Generated by Django 4.2 on 2023-08-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_alter_circle_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='privacy',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=10),
        ),
    ]
