# Generated by Django 4.2 on 2023-08-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_alter_circle_privacy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circlepost',
            options={'ordering': ['-created_at']},
        ),
    ]
