# Generated by Django 4.2 on 2023-09-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_alter_profile_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowerCountHistory',
        ),
    ]
