# Generated by Django 4.2 on 2023-09-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circlepost',
            name='image',
        ),
        migrations.AddField(
            model_name='circlepost',
            name='img',
            field=models.ImageField(blank=True, upload_to='circle_post_images/'),
        ),
    ]
